# On push [1]
# [1] https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on: [push]
jobs:
  rescuezilla-iso-build:
    # The build bot OS environment does not really matter, as the docker image
    # provides the primary host environment for the build. However, a more recent
    # OS provides a more recent Docker release, which means additional Docker
    # functionality.
    # Launches Docker container to act as 'host system'. See BUILD.ISO.IMAGE.md for more information.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true
          fetch-depth: 0

      # Get deb package version using same command from its build scripts
      - run: echo "DEB_VERSION=$(git describe --tags  --match='[0-9].[0-9]*' --abbrev=0)" >> $GITHUB_ENV

      - name: Build Docker image
        run: make docker-build

      - name: Launch Docker container
        run: make docker-run

      - name: Trust the git folder
        run: make docker-add-safe-directory

      - name: Create completed artifacts folder
        run: mkdir completed-artifacts/

      - name: Make DEB package
        run: make docker-deb
      - run: sudo mv build/rescuezilla_${{env.DEB_VERSION}}-1_all.deb completed-artifacts/rescuezilla_${{env.DEB_VERSION}}-1_all.deb

      - name: Make Ubuntu 24.04 LTS (Noble) ISO
        run: make docker-noble
      - run: sudo mv build/rescuezilla.amd64.noble.iso completed-artifacts/rescuezilla-${{github.ref_name}}-64bit.noble.iso
      - run: sudo make clean-all

      - name: Create checksums for ISO images
        run: cd completed-artifacts && sudo ../src/scripts/create-iso-checksums.sh rescuezilla_${{env.DEB_VERSION}}-1_all.deb  rescuezilla-${{github.ref_name}}-*.iso

      - name: Upload release assets (on tag push)
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        with:
          files: |
            completed-artifacts/*SUM
            completed-artifacts/rescuezilla_${{env.DEB_VERSION}}-1_all.deb
            completed-artifacts/rescuezilla-${{github.ref_name}}-*.iso

      # Upload GitHub Action workflow *artifacts*. Note "artifacts" are a different concept to GitHub release rssets. The former is available on each GitHub Actions
      # workflow run. The latter is associated with only a pushed tag.

      - uses: actions/upload-artifact@v4
        with:
          name: SHA256SUM
          path: completed-artifacts/SHA256SUM

      - uses: actions/upload-artifact@v4
        with:
          name: rescuezilla_${{env.DEB_VERSION}}-1_all.deb
          path: completed-artifacts/rescuezilla_${{env.DEB_VERSION}}-1_all.deb

      - uses: actions/upload-artifact@v4
        with:
          name: rescuezilla-${{github.ref_name}}-64bit.noble.iso
          path: completed-artifacts/rescuezilla-${{github.ref_name}}-64bit.noble.iso
